name: yor


on:
  push:
  pull_request:

jobs:
  yor:
  
    permissions:
      contents: read # for actions/checkout to fetch code
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
